# Generated by Django 2.1.3 on 2019-03-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
