# Generated by Django 2.1.3 on 2019-03-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='title2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
