# Generated by Django 2.1.3 on 2019-04-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_post_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile_pic',
            field=models.ImageField(blank=True, default=1, upload_to='profile_image'),
            preserve_default=False,
        ),
    ]
