# Generated by Django 2.1.3 on 2019-04-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_auto_20190425_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_pic',
        ),
    ]
