# Generated by Django 2.1.3 on 2019-04-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_remove_post_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ppic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
