# Generated by Django 2.1.3 on 2019-05-12 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0020_user_plans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplan',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userplan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
