# Generated by Django 2.1.3 on 2019-05-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_auto_20190512_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='id',
        ),
        migrations.AlterField(
            model_name='userplan',
            name='plan',
            field=models.PositiveIntegerField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
